blueprint:
  name: Hello World
  description: A simple blueprint to test functionality.
  domain: automation
  input:
    trigger_entity:
      name: Trigger Entity
      description: The entity that will trigger this automation.
      selector:
        entity: {}
    message:
      name: Message
      description: The message to display when the automation triggers.
      default: "Hello, World!"
      selector:
        text: {}

trigger:
  - platform: state
    entity_id: !input trigger_entity

action:
  - service: notify.persistent_notification
    data:
      message: !input message
      title: "Hello World Notification"
